platform :ios, '8.0'

target 'Example' do
  #pod 'GPJDataDrivenTableView', :git => 'git@github.com:gongpengjun/GPJDataDrivenTableView.git', :tag => 'v1.0.0'
  pod 'GPJDataDrivenTableView', :path => '../../GPJDataDrivenTableView.podspec'
  pod 'randomColor'
  pod 'Masonry'
end
